### ISSUE TITLE
halting problem

### ISSUE THREAD

**Issue by RainbowUnicon** [webrown/PISA#2]
I am completely sure about the origin of this problem. 

But if I run this code with single cache(2 offset, 0 ways and 0 index), then program doesn't end. 

CPY xA R1
LOD R1 R2
CPY xB R1
LOD R1 R3
CPY xC R1
LOD R1 R4
CPY xD R1
LOD R1 R5

#DATA
xA:
1f
xB: 
-4 
xC:
4286578688 
xD:
1065353216

How to duplicate this issue:
After run this code with cache, click step button.

**Comment by webrown** [comment]
I think I fixed it!  Pull and try again.
Good catch!

Best,
-Walter
