### ISSUE TITLE
Delay for instruciton.

### ISSUE THREAD

**Issue by RainbowUnicon** [webrown/PISA#3]
In Baseline.cpp
I think it doesn't consider the delay for instrucitons... Am I correct?

**Comment by webrown** [comment]
Hi Young,
Which delay are you referring to?
Baseline does keep track of the number of cycles that pass.  Most
instructions have a *wait pointer where they can set how many cycles it
took to complete them.
Best,
-Walter

**Comment by RainbowUnicon** [comment]
In Baseline, when you "fetch" the instruction, I think you didn't set the delay for the instruction.

**Comment by webrown** [comment]
Yes, that is correct!
I only did the time it took for instructions to actually execute.

**Comment by RainbowUnicon** [comment]
I think fetching instruction should also take time... Or else, there is no reason to have instruction cache...

**Comment by webrown** [comment]
I agree, especially for pipeline.  I'll put in the change this weekend.

**Comment by RainbowUnicon** [comment]
So I guess the CPI that we demonstrated in last demo was wrong. lol

**Comment by webrown** [comment]
weeeeell it was going to be wrong no matter what.  No pipeline was present
and I totally made up numbers for instruction duration! :)

**Comment by webrown** [comment]
Ironically, this will probably be a 2 line fix! :D

**Comment by RainbowUnicon** [comment]
Thanks. I will close this thread.

**Comment by webrown** [comment]
Not yet, let's wait for the weekend when the fix goes it

**Comment by webrown** [comment]
I'll forget otherwise! :D

**Comment by webrown** [comment]
Does 2 code lines + 1 comment count as a 2-line fix?
Anyway, Pushed!
Thanks for catching that Young!
Have a great weekend,
-Walter

**Comment by RainbowUnicon** [comment]
We count that as 2.5 lines.
