### ISSUE TITLE
TOF broken?

### ISSUE THREAD

**Issue by webrown** [webrown/PISA#6]
CPY 22 R0
CPY 7 R1
TOF R0 R10
TOF R1 R11

DIV R1 R0
DIV R11 R10

add 0 R0
add 0 R0
add 0 R0
add 0 R0
add 0 R0
; We expect that R10 would be 3.14 and R11 would be 7 in floating point.
; However, the values here are nan and 0
; Probably this is a TOF issue, as we would expect that R11 would be 7 in floating point.

**Comment by RainbowUnicon** [comment]
Fixed...
